version: "3.9"

services:
  postgres:
    container_name: postgres_auth
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER_AUTH} # Имя пользователя БД (берётся из .env)
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_AUTH} # Пароль пользователя БД (из .env)
      POSTGRES_DB: ${POSTGRES_DB_AUTH} # Имя БД (из .env)
      PGDATA: /var/lib/postgresql/data # Путь к данным внутри контейнера
    volumes:
      - ./postgres_data:/var/lib/postgresql/data # Локальная папка для хранения данных БД
    ports:
      - "5432:5432" # Проброс порта БД наружу
    networks:
      - app-net

  auth:
    container_name: auth
    build:
      context: . # Контекст сборки — папка с Dockerfile сервиса auth
      dockerfile: ./services/auth/Dockerfile # Имя Dockerfile (по умолчанию можно не указывать)
    env_file:
      - ./.env # Путь к .env (относительно ./services/auth/Dockerfile)
    ports:
      - "8000:8000" # Проброс порта приложения наружу
    depends_on:
      - postgres # Запускать после postgres
    networks:
      - app-net
    volumes:
      - ./pkg/configs/ssl:/app/pkg/configs/ssl # Проброс папки с сертификатами внутрь контейнера
      - ./.env:/app/.env # Проброс .env внутрь контейнера

networks:
  app-net:
    driver: bridge
